# Generated by Django 5.0.2 on 2025-10-06 09:57

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="İsim")),
                ("content", models.TextField()),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                ("price", models.CharField(max_length=50, verbose_name="Fiyat")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rap", "Rap"),
                            ("funk", "Funk"),
                            ("trap", "Trap"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ArticleFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=article.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_author",
                    models.CharField(max_length=50, verbose_name="İsim"),
                ),
                (
                    "comment_content",
                    models.CharField(max_length=200, verbose_name="Yorum"),
                ),
                ("comment_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-comment_date"],
            },
        ),
    ]
