# Generated by Django 5.0.2 on 2025-10-20 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="article",
        ),
        migrations.CreateModel(
            name="Beat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("bpm", models.PositiveIntegerField(default=120)),
                ("key", models.CharField(blank=True, max_length=10)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic License"),
                            ("premium", "Premium License"),
                            ("exclusive", "Exclusive License"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="beats/originals/")),
                (
                    "watermark_file",
                    models.FileField(
                        blank=True, null=True, upload_to="beats/watermarks/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="beat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="article.beat",
                verbose_name="Makale",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ArticleFile",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
