# Generated by Django 5.0.2 on 2026-03-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_remove_article_author_remove_comment_article_beat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beat",
            name="file",
        ),
        migrations.RemoveField(
            model_name="beat",
            name="watermark_file",
        ),
        migrations.AddField(
            model_name="beat",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="beats/"),
        ),
        migrations.AddField(
            model_name="beat",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
    ]
