# Generated by Django 5.0.2 on 2024-08-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0003_article_file_alter_article_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="sarkilar/"),
        ),
    ]
