# Generated by Django 5.0.2 on 2026-04-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_remove_beat_file_remove_beat_watermark_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="exclusive_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="beat",
            name="exclusive_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="beat",
            name="premium_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
