# Generated by Django 5.0.2 on 2026-04-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_beat_exclusive_available_beat_exclusive_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeatLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic License"),
                            ("premium", "Premium License"),
                            ("exclusive", "Exclusive License"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_wav", models.BooleanField(default=False)),
                ("allow_stems", models.BooleanField(default=False)),
                ("commercial_use", models.BooleanField(default=True)),
                (
                    "distribution_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("streaming_limit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "max_purchasers",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank for unlimited purchases.",
                        null=True,
                    ),
                ),
                ("requires_credit", models.BooleanField(default=True)),
                ("sold", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="article.beat",
                    ),
                ),
            ],
            options={
                "ordering": ["price", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="beatlicense",
            constraint=models.UniqueConstraint(
                fields=("beat", "license_type"), name="unique_license_type_per_beat"
            ),
        ),
    ]
