# Generated by Django 5.0.2 on 2024-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0005_remove_article_file_alter_article_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="price",
            field=models.CharField(default=0, max_length=50, verbose_name="Fiyat"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="type",
            field=models.CharField(default=0, max_length=50, verbose_name="Type"),
            preserve_default=False,
        ),
    ]
