# Generated by Django 5.0.2 on 2026-03-30 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_remove_beat_file_remove_beat_watermark_file_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_amount",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="order",
            name="beat",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="article.beat",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("exclusive", "Exclusive"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_provider",
            field=models.CharField(default="mock_iyzico", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
