# Generated by Django 5.0.2 on 2026-04-08 22:47

import orders.models
from django.db import migrations, models
from uuid import uuid4


def copy_existing_order_data(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")

    for order in Order.objects.all():
        if getattr(order, "beat_id", None) is None:
            continue
        if OrderItem.objects.filter(order_id=order.id).exists():
            continue

        OrderItem.objects.create(
            order_id=order.id,
            beat_id=order.beat_id,
            beat_title=order.beat.title,
            selected_license=order.license_type,
            unit_price=order.amount,
            quantity=1,
        )


def populate_tracking_codes(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    existing_codes = set(
        Order.objects.exclude(tracking_code__isnull=True)
        .exclude(tracking_code="")
        .values_list("tracking_code", flat=True)
    )

    for order in Order.objects.all():
        if order.tracking_code:
            continue

        code = uuid4().hex[:12].upper()
        while code in existing_codes:
            code = uuid4().hex[:12].upper()

        order.tracking_code = code
        order.save(update_fields=["tracking_code"])
        existing_codes.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_total_amount_order_amount_order_beat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="TRY", max_length=10),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(
                editable=False,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("fulfilled", "Fulfilled"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(copy_existing_order_data, migrations.RunPython.noop),
        migrations.RunPython(populate_tracking_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(
                default=orders.models.generate_tracking_code,
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
        migrations.RemoveField(
            model_name="order",
            name="beat",
        ),
        migrations.RemoveField(
            model_name="order",
            name="license_type",
        ),
    ]
