# Generated by Django 5.0.2 on 2026-04-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_beatlicense_beatlicense_unique_license_type_per_beat"),
        ("orders", "0003_remove_order_beat_remove_order_license_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="beat_license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="article.beatlicense",
            ),
        ),
    ]
